api:
  url: http://172.16.67.130:8000/django_ca/api/cert/
  token: 7b51d4a3897add72c7231c7d75227e6f77e35a8e
csr:
  algorithm: sha256
  cn: web01.server.example.com
  san:
    - 192.168.1.1
    - www.example.com
    - "*.somedomain.com"
    - 10.21.123.141
    - "*.new.domain"
    - servername
  subject:
    C: UK
    ST: Cheshire
    L: Stockport
    O: CDL
    OU: Strata Admin
    emailAddress: strataadmin@cdl.co.uk
certs:
  ca: 2
  keybits: 2048
  path: certs
  regen: 7
logging:
  path: logs
  level: WARN
